spring.application.name=sistema-turnos
#conexion a sql
spring.datasource.url=jdbc:mysql://localhost:3306/sistema_turnos
spring.datasource.username=root
spring.datasource.password=Juancruz1_

# Driver de MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialecto de MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect